CREATE TABLE [dbo].[tblIngredient]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Name] VARCHAR(50) NOT NULL, 
    [TypeId] INT NOT NULL,
    [SysStart] DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
	[SysEnd] DATETIME2 (7) GENERATED ALWAYS AS ROW END NOT NULL,
	PERIOD FOR SYSTEM_TIME ([SysStart], [SysEnd])
    ,CONSTRAINT [FK_tblIngredient_tblIngredientType] FOREIGN KEY ([TypeId]) REFERENCES [tblIngredientType]([Id])    
)
WITH (SYSTEM_VERSIONING = ON(HISTORY_TABLE=[dbo].[tblIngredient_HISTORY], DATA_CONSISTENCY_CHECK=ON))
